### PR TITLE
add info card to herd form and fix styling

### LINKED ISSUE #412: Info text on herd page information
Information text for herd users.

**Det ska finnas en inforuta på sidan med följande text:**
Du som är genbanksinnehavare fyller själv i de kontaktuppgifter du vill att andra
genbanker ska se för att underlätta kommunikation mellan genbankerna. Du kan själv,
när som helst, gå in och ändra i dina kontaktuppgifter. OBS! En ändring här slår inte
igenom till föreningens medlemsmatrikel, så om du exempelvis flyttat eller bytt e-post,
måste du också meddela det till föreningens kassör, för ändring i medlemsmatrikeln.
Medlemsmatrikeln används bara för föreningens interna administration, och är inte
offentlig.

### PR DESCRIPTION
**Pull request by HenrikeW**
I added the info text as a box in herd form. 
It's rendered to the right of the forms boxes. 
If there is not enough space, it will wrap to below.

I also changed the styling slightly to make the first form box look better. 

This fixes #412

### CODE REVIEW

File: frontend/src/herdForm.tsx [hunk 1]
```diff
@@ -447,6 +447,29 @@ export function HerdForm({
                       </Typography>
                     </div>
                   </MuiPickersUtilsProvider>
+                  <div className="formCard formInfoCard">
+                    <Typography className="subheading">
+                      Du bestämmer över dina uppgifter
+                    </Typography>
+                    <p>
+                      Du som är genbanksinnehavare fyller själv i de
```
Comment (jhagberg) [inline frontend/src/herdForm.tsx]: ändra till "Du som är besättningsinnehavare"

File: frontend/src/herdForm.tsx [hunk 2]
```diff
@@ -447,6 +447,29 @@ export function HerdForm({
...
+                      kontaktuppgifter du vill att andra genbanker ska se för
+                      att underlätta kommunikation mellan genbankerna. Du kan
```
Comment (jhagberg) [inline frontend/src/herdForm.tsx]: Mellan besättningarna

**Review by jhagberg — CHANGES_REQUESTED** [review]

**Review by jhagberg — APPROVED** [review]
Looks very good!
